// This file is auto-generated by @hey-api/openapi-ts

export type Message = {
  message: string;
};

export type PaginatedUserList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<User>;
};

export type PatchedUser = {
  readonly id?: number;
  email?: string;
  /**
   * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
   */
  is_active?: boolean;
  /**
   * Designates whether the user can log into this admin site.
   */
  is_staff?: boolean;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   */
  is_superuser?: boolean;
  readonly created?: string;
  readonly modified?: string;
  last_login?: string | null;
};

export type User = {
  readonly id: number;
  email: string;
  /**
   * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
   */
  is_active?: boolean;
  /**
   * Designates whether the user can log into this admin site.
   */
  is_staff?: boolean;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   */
  is_superuser?: boolean;
  readonly created: string;
  readonly modified: string;
  last_login?: string | null;
};

export type ApiRestRestCheckRetrieveResponse = Message;

export type ApiUsersListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type ApiUsersListResponse = PaginatedUserList;

export type ApiUsersCreateData = {
  requestBody: User;
};

export type ApiUsersCreateResponse = User;

export type ApiUsersRetrieveData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type ApiUsersRetrieveResponse = User;

export type ApiUsersUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody: User;
};

export type ApiUsersUpdateResponse = User;

export type ApiUsersPartialUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody?: PatchedUser;
};

export type ApiUsersPartialUpdateResponse = User;

export type ApiUsersDestroyData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type ApiUsersDestroyResponse = void;

export type $OpenApiTs = {
  "/api/rest/rest-check/": {
    get: {
      res: {
        200: Message;
      };
    };
  };
  "/api/users/": {
    get: {
      req: ApiUsersListData;
      res: {
        200: PaginatedUserList;
      };
    };
    post: {
      req: ApiUsersCreateData;
      res: {
        201: User;
      };
    };
  };
  "/api/users/{id}/": {
    get: {
      req: ApiUsersRetrieveData;
      res: {
        200: User;
      };
    };
    put: {
      req: ApiUsersUpdateData;
      res: {
        200: User;
      };
    };
    patch: {
      req: ApiUsersPartialUpdateData;
      res: {
        200: User;
      };
    };
    delete: {
      req: ApiUsersDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
};
